apiVersion: apps/v1
kind: Deployment
metadata:
  name: person
spec:
  replicas: 2
  selector:
    matchLabels:
      app: person
  template:
    metadata:
      labels:
        app: person
    spec:
      containers:
      - name: person
        image: rkm508/person:latest
        ports:
        - containerPort: 8081   # updated to match your app
